name: Run Katalon Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  katalon-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download Katalon Studio
        run: |
          wget https://github.com/katalon-studio/katalon-studio/releases/download/v9.3.0/Katalon_Studio_Engine_Linux_64-9.3.0.tar.gz
          mkdir katalon
          tar -xvzf Katalon_Studio_Engine_Linux_64-9.3.0.tar.gz -C katalon

      - name: Run Katalon Tests
        run: |
          ./katalon/Katalon_Studio_Engine_Linux_64-9.3.0/katalonc \
            -noSplash \
            -runMode=console \
            -projectPath="$(pwd)/test.prj" \
            -retry=0 \
            -testSuitePath="Test Suites/google" \
            -executionProfile="default" \
            -browserType="ChromeHeadless" \
            -apiKey="${{ secrets.KATALON_API_KEY }}"
